{host, ...}: let
  inherit
    (import ../../../hosts/${host}/variables.nix)
    browser
    terminal
    ;
in {
  wayland.windowManager.hyprland.settings = {
    bind = [
      "SUPER,Return,exec,${terminal}"
      "SUPER,K,exec,list-keybinds"
      "SUPER SHIFT,Return,exec,rofi-launcher"
      "SUPER SHIFT,W,exec,web-search"
      "SUPER ALT,W,exec,wallsetter"
      "SUPER SHIFT,N,exec,swaync-client -rs"
      "SUPER,W,exec,${browser}"
      "SUPER,Y,exec,kitty -e yazi"
      "SUPER,E,exec,code"
      "SUPER,R,exec,emopicker9000"
      "SUPER,S,exec,screenshootin"
      "SUPER,D,exec,discord"
      "SUPER,L,exec,hyprlock"
      "SUPER,C,exec,hyprpicker -a"
      "SUPER,G,exec,gedit"
      "SUPER,T,exec,pypr toggle term"
      "SUPER,M,exec,pavucontrol"
      "SUPER,Q,killactive,"
      "SUPER,P,pseudo,"
      "SUPER,F,fullscreen,"
      "SUPER SHIFT,F,togglefloating,"
      "SUPER ALT,F,workspaceopt, allfloat"
      "SUPER SHIFT,C,exit,"
      "SUPER SHIFT,left,movewindow,l"
      "SUPER SHIFT,right,movewindow,r"
      "SUPER SHIFT,up,movewindow,u"
      "SUPER SHIFT,down,movewindow,d"
      "SUPER SHIFT,h,movewindow,l"
      "SUPER SHIFT,l,movewindow,r"
      "SUPER SHIFT,k,movewindow,u"
      "SUPER SHIFT,j,movewindow,d"
      "SUPER ALT, left, swapwindow,l"
      "SUPER ALT, right, swapwindow,r"
      "SUPER ALT, up, swapwindow,u"
      "SUPER ALT, down, swapwindow,d"
      "SUPER ALT, 43, swapwindow,l"
      "SUPER ALT, 46, swapwindow,r"
      "SUPER ALT, 45, swapwindow,u"
      "SUPER ALT, 44, swapwindow,d"
      "SUPER,left,movefocus,l"
      "SUPER,right,movefocus,r"
      "SUPER,up,movefocus,u"
      "SUPER,down,movefocus,d"
      "SUPER,h,movefocus,l"
      "SUPER,l,movefocus,r"
      "SUPER,k,movefocus,u"
      "SUPER,j,movefocus,d"
      "SUPER,1,workspace,1"
      "SUPER,2,workspace,2"
      "SUPER,3,workspace,3"
      "SUPER,4,workspace,4"
      "SUPER,5,workspace,5"
      "SUPER,6,workspace,6"
      "SUPER,7,workspace,7"
      "SUPER,8,workspace,8"
      "SUPER,9,workspace,9"
      "SUPER,0,workspace,10"
      "SUPER SHIFT,SPACE,movetoworkspace,special"
      "SUPER,SPACE,togglespecialworkspace"
      "SUPER SHIFT,1,movetoworkspace,1"
      "SUPER SHIFT,2,movetoworkspace,2"
      "SUPER SHIFT,3,movetoworkspace,3"
      "SUPER SHIFT,4,movetoworkspace,4"
      "SUPER SHIFT,5,movetoworkspace,5"
      "SUPER SHIFT,6,movetoworkspace,6"
      "SUPER SHIFT,7,movetoworkspace,7"
      "SUPER SHIFT,8,movetoworkspace,8"
      "SUPER SHIFT,9,movetoworkspace,9"
      "SUPER SHIFT,0,movetoworkspace,10"
      "SUPER CONTROL,right,workspace,e+1"
      "SUPER CONTROL,left,workspace,e-1"
      "SUPER,mouse_down,workspace, e+1"
      "SUPER,mouse_up,workspace, e-1"
      "ALT,Tab,cyclenext"
      "ALT,Tab,bringactivetotop"
      ",XF86AudioRaiseVolume,exec,wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"
      ",XF86AudioLowerVolume,exec,wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"
      " ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
      ",XF86AudioPlay, exec, playerctl play-pause"
      ",XF86AudioPause, exec, playerctl play-pause"
      ",XF86AudioNext, exec, playerctl next"
      ",XF86AudioPrev, exec, playerctl previous"
      ",XF86MonBrightnessDown,exec,brightnessctl set 5%-"
      ",XF86MonBrightnessUp,exec,brightnessctl set +5%"
    ];

    bindm = [
      "SUPER, mouse:272, movewindow"
      "SUPER, mouse:273, resizewindow"
    ];
  };
}
