{pkgs, ...}: {
  environment.systemPackages = with pkgs; [
    mission-center
    onlyoffice-desktopeditors
    enpass
    restic
    rclone
    dropbox
    remmina
    teamviewer
    rustdesk
    ansible
    vagrant
    mc
    postman
    nmap
    python313
    python313Packages.requests
    python313Packages.flask
    python313Packages.fastapi
    gnome-disk-utility
    nwg-displays
    putty
    kubectl
    _7zz
    inetutils
    opentofu
  ];
}
