{pkgs, ...}: {
  environment.systemPackages = with pkgs; [
    mission-center
    onlyoffice-desktopeditors
    teams-for-linux
    enpass
    restic
    rclone
    dropbox
    zerotierone
    openfortivpn
    openvpn
    wireguard-tools
    remmina
    teamviewer
    rustdesk
    winbox4
    ansible
    virtualbox
    vagrant
    mc
    postman
    nmap
    python313
    python313Packages.requests
    python313Packages.flask
    python313Packages.fastapi
    gnome-disk-utility
    nwg-displays
    putty
    kubectl
  ];
}
