{inputs, ...}: {
  imports = [
    ./boot.nix
    ./distributed_build.nix
    ./flatpak.nix
    ./fonts.nix
    #./greetd.nix
    ./hardware.nix
    ./network.nix
    ./nfs.nix
    ./nh.nix
    ./packages.nix
    ./printing.nix
    ./sddm.nix
    ./security.nix
    ./services.nix
    ./starfish.nix
    ./stylix.nix
    ./syncthing.nix
    ./system.nix
    ./thunar.nix
    ./user.nix
    ./virtualisation.nix
    ./wireshark.nix
    ./winbox.nix
    ./xserver.nix
    inputs.stylix.nixosModules.stylix
  ];
}
